apiVersion: v2
name: microservices-umbrella
description: Umbrella chart for the full microservice stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: api-gateway
    version: "0.1.0"
    repository: "file://../../api-gateway/helm"
  - name: auth-service
    version: "0.1.0"
    repository: "file://../../auth-service/helm"
  - name: inventory-service
    version: "0.1.0"
    repository: "file://../../inventory-service/helm"
  - name: order-service
    version: "0.1.0"
    repository: "file://../../order-service/helm"
  - name: product-service
    version: "0.1.0"
    repository: "file://../../product-service/helm"
  - name: user-service
    version: "0.1.0"
    repository: "file://../../user-service/helm"