api-gateway:
  replicaCount: 1
  image:
    repository: ghcr.io/monstacupcake37/api-gateway
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
auth-service:
  replicaCount: 1
  image:
    repository: ghcr.io/monstacupcake37/auth-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
inventory-service:
  replicaCount: 1
  image:
    repository: ghcr.io/monstacupcake37/inventory-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
order-service:
  replicaCount: 1
  image:
    repository: ghcr.io/monstacupcake37/order-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
product-service:
  replicaCount: 1
  image:
    repository: ghcr.io/monstacupcake37/product-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
user-service:
  replicaCount: 1
  image:
    repository: ghcr.io/monstacupcake37/user-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
notification-service:
  replicaCount: 1
  image:
    repository: ghcr.io/monstacupcake37/notification-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080