name: Reusable - CI/CD Pipeline for a Microservice

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  checkstyle-test-coverage-threshold-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' 
      
      - name: Run checkstyle, tests, coverage & threshold check
        run: mvn verify -f ./${{ inputs.service_name }}/pom.xml
      
  build-push:
    runs-on: ubuntu-latest
    needs: checkstyle-test-coverage-threshold-check
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' 
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}
          tags: |
            type=ref,event=branch
            type=sha,format=short
      - uses: docker/build-push-action@v7
        with:
          context: ./${{ inputs.service_name }}
          file: ./${{ inputs.service_name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
