name: Build & Push api-gateway

on:
  push:
    paths: ['.github/workflows/_ci-service.yml', '.github/workflows/api-gateway.yml', 'api-gateway/**', '!api-gateway/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['./.github/workflows/_ci-service.yml', './.github/workflows/api-gateway.yml', 'api-gateway/**', '!api-gateway/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_ci-service.yml
    with:
      service_name: api-gateway
    secrets: inherit
