name: Build & Push auth-service

on:
  push:
    paths: ['.github/workflows/_ci-service.yml', '.github/workflows/auth-service.yml', 'auth-service/**', '!auth-service/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['.github/workflows/_ci-service.yml', '.github/workflows/auth-service.yml', 'auth-service/**', '!auth-service/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_ci-service.yml
    with:
      service_name: auth-service
    secrets: inherit
