name: Build & Push auth-service

on:
  push:
    paths: ['auth-service/**', '!auth-service/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['auth-service/**', '!auth-service/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_build-and-push-service.yml
    with:
      service_name: auth-service
    secrets: inherit
