name: Build & Push order-service

on:
  push:
    paths: ['inventory-service/**']
    branches: [ main ]
  pull_request:
    paths: ['inventory-service/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_build-and-push-service.yml
    with:
      service_name: inventory-service
    secrets: inherit
