name: Build & Push inventory-service

on:
  push:
    paths: ['inventory-service/**', '!inventory-service/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['inventory-service/**', '!inventory-service/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_ci-service.yml
    with:
      service_name: inventory-service
    secrets: inherit
