name: Build & Push notification-service

on:
  push:
    paths: ['.github/workflows/_ci-service.yml', '.github/workflows/notification-service.yml', 'notification-service/**', '!notification-service/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['.github/workflows/_ci-service.yml', '.github/workflows/notification-service.yml', 'notification-service/**', '!notification-service/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_ci-service.yml
    with:
      service_name: notification-service
    secrets: inherit
