name: Build & Push order-service

on:
  push:
    paths: ['notification-service/**']
    branches: [ main ]
  pull_request:
    paths: ['notification-service/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_build-and-push-service.yml
    with:
      service_name: notification-service
    secrets: inherit
