name: Build & Push product-service

on:
  push:
    paths: ['product-service/**', '!product-service/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['product-service/**', '!product-service/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_build-and-push-service.yml
    with:
      service_name: product-service
    secrets: inherit
