name: Build & Push product-service

on:
  push:
    paths: ['./.github/workflows/_ci-service.yml', './.github/workflows/product-service.yml', 'product-service/**', '!product-service/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['./.github/workflows/_ci-service.yml', './.github/workflows/product-service.yml', 'product-service/**', '!product-service/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_ci-service.yml
    with:
      service_name: product-service
    secrets: inherit
