name: Build & Push user-service

on:
  push:
    paths: ['./.github/workflows/_ci-service.yml', './.github/workflows/user-service.yml', 'user-service/**', '!user-service/helm/**']
    branches: [ main ]
  pull_request:
    paths: ['./.github/workflows/_ci-service.yml', './.github/workflows/user-service.yml', 'user-service/**', '!user-service/helm/**']
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/_ci-service.yml
    with:
      service_name: user-service
    secrets: inherit
